server: "hub-cloud.browserstack.com"

common_caps:
  "build": "OSX Snow Leopard Firefox 38 ESR"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false
  "browserstack.selenium_version": "2.45.0"

browser_caps:
  -
    "browser": "firefox"
    "browser_version": "38.0"
    "os": "osx"
    "os_version": "snow leopard"