beef:
    module:
        detect_local_settings:
            enable: true
            category: "Network"
            name: "Detect local settings"
            description: "Grab the local network settings (ie internal ip address)."
            authors: ["pdp", "wade", "bm"]
            target:
                working: ["FF", "C"]
                not_working: ["IE"]