server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows 10 Chrome 51"
  "project": "BeEF"
  "browserstack.local": true

browser_caps:
  -
    "browser": "chrome"
    "browser_version": "51.0"
    "os": "windows"
    "os_version": "10"