server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows 10 Chrome Latest"
  "project": "BeEF"
  "browserstack.local": true

browser_caps:
  -
    "browser": "chrome"
    "os": "windows"
    "os_version": "8.1"