server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows Chrome Latest"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false

browser_caps:
  -
    "browser": "chrome"
    "os": "windows"