server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows Edge"
  "name": "BStack Test Run"
  "project": "My Project"
  "browserstack.local": true

browser_caps:
  -
    "browser": "edge"
    "os": "Windows"