beef:
    module:
        iphone_tel:
            enable: true
            category: "Host"
            name: "iPhone Telephone URL"
            description: "This module will force the browser to attempt a skype call. It will exploit the insecure handling of URL schemes in iOS.<br><br>The protocol handler used will be: tel"
            authors: ["xntrik", "Nitesh Dhanjani"]
            target:
                working: ['S']
