beef:
    module:
        insecure_url_skype:
            enable: true
            category: "Host"
            name: "Insecure URL Handling - Skype Call"
            description: "This module will force the browser to attempt a skype call. It will exploit the insecure handling of URL schemes<br><br>The protocol handler used will be: skype."
            authors: ["xntrik", "Nitesh Dhanjani"]
            target:
                working: ['S']
                user_notify: ['C', 'FF', 'O']
