beef:
    module:
        detect_tor:
            enable: true
            category: "Recon"
            name: "Detect Tor" 
            description: "This module will detect if the zombie is currently using TOR (The Onion Router)."
            authors: ["wade", "pdp", "bm", "xntrik"]
            target:
                working: ["ALL"]
