language: ruby
rvm:
- 2.5.3
- 2.6.0
- 2.6.3
- 2.6.5
- 2.7.0
branches:
  only:
  - master
  - browserstack
before_script:
  - cat /home/travis/.rvm/gems/ruby-2.5.3/gems/browserstack-local-1.3.0/lib/browserstack/local.rb
  - sed -i -E 's/system\((.*?)\)/""/g' /home/travis/.rvm/gems/ruby-2.5.3/gems/browserstack-local-1.3.0/lib/browserstack/local.rb
  - cat /home/travis/.rvm/gems/ruby-2.5.3/gems/browserstack-local-1.3.0/lib/browserstack/local.rb
script:
  # - bundle exec rake
  - CONFIG_NAME='windows/windows_chrome_latest.config.yml' bundle exec rspec --tag run_on_browserstack
  - CONFIG_NAME='osx/osx_safari_latest.config.yml' bundle exec rspec --tag run_on_browserstack
addons:
  apt:
    packages:
    - libsqlite3-dev
    - build-essential
    - patch
    - ruby-dev
    - zlib1g-dev
    - liblzma-dev
    - libcurl4-openssl-dev
  browserstack:
    username:
      secure: "llHTOE7kdDo+4QBcZnajVlQk1rQR0sglaW49w6/BH6Gy8x026K6am62Mneoo8+T6jySfYspADatuQdxlSzrpx5TG/YU6HJf2F4TlaEWZMBwj53U+icKgqnzLFp6VDAi8Ts8pVGYhjtyjeQ7xLvwKC0uf1ZzgDo3LhbukfaHc+Gg9AHZULv7aY24n0SGy76NzC55K2lJG6T+d4aWuOfEuyeWgv7xhr8wJVy7Qf00Z9j8zGQRjkxaeFiEdtGV1yTZ1t0vIIbimBeFqf6hkewFxo2gm8JkB/D3n9E3zczgzKEB0rNYaAkTCmWPzATdsmhaSAgGftJiRlaC/QXCa7Qp3iGVcP8dUw4B4vEviePCejEm2g8GYBQiC8dXHiuI14m0o5WHR2TIxEtb39rpH6XNfp+KDugDoYU8NCVk4CNOKXvMRazMFyFQCqp8q7npi7x7SDMzHwim+7PIp1u0KnP6cctbgrzKrjTh8KfXN+HXVtJaBCFJKJBxuHNePWYm0pPj2MdvQE/N0gK9QPWSEeeQ+hxxMRng991OF1+nXVmXax7S7b27pQUdFsd17yvMvM8VQiTHWEKspVH66rFvh6QOeDYAbN9jt22xgdeiXl9Goz3ULltqifr8U69dVf7DgpSq2z7BKEjKtfXTIquhSxtGaMvXOD9m7PxDrxK6cH1PMXqs="
    access_key:
      secure: "V6iNFxjcgDeI2y1PwqhzPW7ooaN+HL6pxlOsFnN7hOGPY4KvfLg2l6yJg7+vMjLcI6OtAFmhTLSNzpw8GyL5BK8JsAdpaoQcRH0E39GF+OsUkgH6rJefjyFl+JwXosl8Cm1aOgELV1b3KKYhqoCB0NUA//gZy12jLVMslqt+qfldW9QXTCqk0BBwCbpm1TcTuORwqF2/NcP2+AChZ+J1kHtjNW8zREhtBqIGg/Z6TlsWaMIXs53lNZEmSLsrBVWQhFhrYnQQQ1TrTasGtkczCfdpH13+V3tmxeRWIqTI0wn1Kmv3Ud+x1a7s4x5SNVEJzr9V5O4WWZAUxYKjZpKSdiSD8faWeXaduETCadHZmectQ3P2GabOQs0hNULTNBWc5DU2dMSqzcHRr8qb3TJJEN0iJDPLKR1Yx+97hd1FziTNemEWVHnoih7l5cl2NjBjfz7bX9c4St58SxISnklD4wR7HbfSq4boYDN0nrHSo76FpsUwyClk8obnpPIxNnOpsEbP66NYn/OUNcM10067H7+YOpR35Z3B5XT8pONfxaUA9kaw/LYaZ6clP7wxom26kZydG67TvKE9c9SOLF98X9e1YLiEAmPv36Yl8JXa/4AV3pVW6iShej5MNDX4RQFCniSADwJCZVLbBnzjsrp48PdYuYBtVEGFnuR4dEWm1hk="