language: ruby
rvm:
- 2.5.3
- 2.6.0
- 2.6.3
- 2.6.5
- 2.7.0
branches:
  only:
  - master
  - browserstack
before_script:
  - RUBY_VERSION=/bin/bash rvm current
  - sed -i -E 's/system\((.*?)\)/""/g' /home/travis/.rvm/gems/$RUBY_VERSION/gems/browserstack-local-1.3.0/lib/browserstack/local.rb
  - yes | ./update-geoipdb
env:
  - CONFIG_FILE=osx/catalina/catalina_chrome_39.config.yml
  # - CONFIG_FILE=osx/catalina/catalina_chrome_59.config.yml
  # - CONFIG_FILE=osx/catalina/catalina_chrome_81.config.yml
  # - CONFIG_FILE=osx/catalina/catalina_firefox_11.config.yml
  # - CONFIG_FILE=osx/catalina/catalina_firefox_68esr.config.yml
  # - CONFIG_FILE=osx/catalina/catalina_firefox_75.config.yml
  # - CONFIG_FILE=osx/catalina/catalina_safari_13.config.yml
  # - CONFIG_FILE=osx/el_capitan/elcapitan_chrome_14.config.yml
  # - CONFIG_FILE=osx/el_capitan/elcapitan_chrome_81.config.yml
  # - CONFIG_FILE=osx/el_capitan/elcapitan_firefox_5.config.yml
  # - CONFIG_FILE=osx/el_capitan/elcapitan_firefox_75.config.yml
  # - CONFIG_FILE=osx/el_capitan/elcapitan_safari_9-1.config.yml
  # - CONFIG_FILE=osx/snow_leopard/snowleopard_chrome_14.config.yml
  # - CONFIG_FILE=osx/snow_leopard/snowleopard_chrome_35.config.yml
  # - CONFIG_FILE=osx/snow_leopard/snowleopard_chrome_49.config.yml
  # - CONFIG_FILE=osx/snow_leopard/snowleopard_firefox_5.config.yml
  # - CONFIG_FILE=osx/snow_leopard/snowleopard_firefox_42.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
  # - CONFIG_FILE=windows/windows_chrome_latest.config.yml
# jobs:
#   include:
#     - name: "Full Test Suite 2.5.3"
#       rvm: 2.5.3
#       script: bundle exec rake
#     - name: "Full Test Suite 2.6.0"
#       rvm: 2.6.0
#       script: bundle exec rake
#     - name: "Full Test Suite 2.6.3"
#       rvm: 2.6.3
#       script: bundle exec rake
#     - name: "Full Test Suite 2.6.5"
#       rvm: 2.6.5
#       script: bundle exec rake
#     - name: "Full Test Suite 2.7.0"
#       rvm: 2.7.0
#       script: bundle exec rake
script:
  - bundle exec rspec --tag run_on_browserstack
addons:
  apt:
    packages:
    - libsqlite3-dev
    - build-essential
    - patch
    - ruby-dev
    - zlib1g-dev
    - liblzma-dev
    - libcurl4-openssl-dev
  browserstack:
    username:
      secure: "ricyJO2L+faqddj2o3+j7NjYNFERxSD2xtc9Lo3GcuFhwpJHix2GcxvSrE9Agze2dUdkvUQAqh2wcbZu69Qlx8hKgr9Didg8AyxBV5IZYJwyqb6H+Z0MjIgMQmaLnvJosJGkT86yBLo0WVxJKFBxOkZfxk8ts0yReJEKDc61JmSAo2Bdl3W+imcYQL28sI3E8VK//ufhC3FiPPlgreKTSmksN7eqDcDTek0mGRlQjBsVn0y3NJIOLWlubKgWy67QIYD66R+uu2Oz+4TntMZ5UrsUlH5RJuNTgqv451HqVjkTrbFwt/2EKAdbDfRIq+zPRhRfLUan0XUSrAf+1WGTklE+c2LpeVR5UI8A4Y8HDN1KoVEZdpC1ItM0nLRk6vVbsJPLzW1mnhcQ7uMn7pHEK/xhHk6qf2sern/MGlX1YDased9RIacZOkBRKka/lPKa64hukvNvIHUCx5nnr67Usy3LR18i5anM2zzFdRLGdm4ABYThZuWRDTh2chyxuPBzLB3DcuN5sOCZLfbl1H9nR3w7QvbwZKV6O9oak+vIVQvb9qVssh0p0GaHc83Ruzx0HTUD6Pl5yDUjV3oK+iy36KYpUfJpQzkuqwyxxwuj8Np71V1AhOFwQr3jERjF7uOS4BGSsDfJj9BrtJVWXcPc20rbRab3GakZhkOI0pKQpAs="
    access_key:
      secure: "slZK7I/Q58nMxN3BfdbgwgbCOz8cDpjmJVvHTHrFzg1Cj8Ndduc+4cx/N37RFIy1TwsGxVxkTnxvfHgpu6cN0PzxO65t/qDOoKVDZws5ubnEOzynqZmXa0n3xg241QfvRAJbSdDLvjP0HIvLxdwd7fuikiWxGZSSjaUf3hgtZEpW6U4Kt98NIIhE2fM5/k/oVI8IsQpG+ulKZ+I9rFlxwBqo10Utjo4yxnOoZfPt8sTzoWqj9wh9Y88ryvDDacuJtJ2AWPOmPzC/wFJK1LJwcaV3YXG6M28xk4KOYBduDD/7+cUO0k0Y0wB4dLrRiX5+H5QVj0aQS6Rb6Sohx6xhoiUyhtk4W2F6QRGBLjChmiZwyMoRRNeZOYxGVB3aPg3O8g+nSmamtWdLi5irnenzyd1oo8qRNHH9LSvIzVUasxYkn3jJUNGjfeN9Iphy3/Ogzbpwxkz+VinXEb1LqBXz1aviGxeYdYqn55SiZvUPAZcbUShCrVG5VLXo1OBMhJoJTkKsMYO5Q1BDpG6XJdzSnzGWdxMqmUErSSkJIMj8McRvSGIiG06yfM8i2FKiltfq9AooMJcURX0bS1KtTFe36/TUxhRLUPc1NglZmVUT3n46ubGR5+k1Qcu3FKSxsSUxgT2xzWGSyNy7E+1r1S9gGvJfaNOvdACpalzb9XKv7rA="