language: ruby
rvm:
  - 2.5.3
  - 2.6.0
  - 2.6.3
  - 2.6.5
  - 2.7.0
# safelist
branches:
  only:
    - master
    - browserstack
addons:
  apt:
    packages:
      - libsqlite3-dev
      - build-essential
      - patch
      - ruby-dev
      - zlib1g-dev
      - liblzma-dev
      - libcurl4-openssl-dev
  browserstack:
    username: "greggregory4"
    access_key: "Vyo52yEzjPkDmqANH6qH"
