language: ruby
rvm:
  - 2.5.3
  - 2.6.0
  - 2.6.3
  - 2.6.5
  - 2.7.0
# safelist
branches:
  only:
    - master
    - browserstack
addons:
  apt:
    packages:
      - libsqlite3-dev
      - build-essential
      - patch
      - ruby-dev
      - zlib1g-dev
      - liblzma-dev
      - libcurl4-openssl-dev
  browserstack:
    username: 'craigdonaldson1'
    access_key:
      secure: 'ayO0krAdcapEPxbs9GyUfN2vDV0974vo+gMIRH4xSJ6/QStV38qfVKaHMMuDcmnLCboFaAnsPdklWfuR4fd5NSO26iOyby4ByjVA6tjO1DwVy31+Aw0Vd1KPLSil4n6eujpSpXqQwYnhCfdex3pgJ4csUGwdR0NPQ/b8PjV2KGzENscdGunYh+o2W67msWT+B3UH0lRVmGMYdUNplVBI3c7iviSAsEMJMSW7mjU3FKEAbsQR9OHscUkt883Axlgal3NxKjODgwaBNjfpVTFWOzcKDy0/eOAEmP02Wi+x1k8TU4zxOduzmiJZ18yYOzPlcbpBD3NSnFB0QbhQmPNRJghenF0zS/pRyAWRRt3r2p+VvbqmOlgcnlf3QaBARqCvCLIM/UpAz+pR0ICumFdP/z7ejX3RJCE/vOrLui+yow6A13yVElvpgbVBdt6uhubVlAblTOYdrooJNSqJh0zvprOcneaF0Di+MEx8FE9hp35YNBL8sdPtoWGWxLgKEmOTZysXj5VtPSnxpJcSSkdRGMBeKULtYVkCd0H+O4pfVvU7UGy6QcwtRO1WNa4VcFUi9m+wZ/Pkhoc1ZB7fv/dX99TEGMjRhqgCsR8VwCVoUlAvU5uhtbajmqoIt8gaK4P/rh+l5+HR+w2qmbfPt+3w1pU2Le8+n+ue5AMe+WcsnHk='