language: ruby
rvm:
- 2.5.3
- 2.6.0
- 2.6.3
- 2.6.5
- 2.7.0
branches:
  only:
  - master
  - browserstack
before_script:
  - RUBY_VERSION=/bin/bash rvm current
  - sed -i -E 's/system\((.*?)\)/""/g' /home/travis/.rvm/gems/$RUBY_VERSION/gems/browserstack-local-1.3.0/lib/browserstack/local.rb
env:
  - CONFIG_FILE=osx/catalina/catalina_chrome_39.config.yml
  - CONFIG_FILE=osx/catalina/catalina_chrome_59.config.yml
  - CONFIG_FILE=osx/catalina/catalina_chrome_81.config.yml
  - CONFIG_FILE=osx/catalina/catalina_firefox_11.config.yml
  - CONFIG_FILE=osx/catalina/catalina_firefox_68esr.config.yml
  - CONFIG_FILE=osx/catalina/catalina_firefox_75.config.yml
  - CONFIG_FILE=osx/catalina/catalina_safari_13.config.yml
  - CONFIG_FILE=osx/el_capitan/elcapitan_chrome_14.config.yml
  - CONFIG_FILE=osx/el_capitan/elcapitan_chrome_81.config.yml
  - CONFIG_FILE=osx/el_capitan/elcapitan_firefox_5.config.yml
  - CONFIG_FILE=osx/el_capitan/elcapitan_firefox_75.config.yml
  - CONFIG_FILE=osx/el_capitan/elcapitan_safari_9-1.config.yml
  - CONFIG_FILE=osx/snow_leopard/snowleopard_chrome_14.config.yml
  - CONFIG_FILE=osx/snow_leopard/snowleopard_chrome_35.config.yml
  - CONFIG_FILE=osx/snow_leopard/snowleopard_chrome_49.config.yml
  - CONFIG_FILE=osx/snow_leopard/snowleopard_firefox_5.config.yml
  - CONFIG_FILE=osx/snow_leopard/snowleopard_firefox_38esr.config.yml
  - CONFIG_FILE=osx/snow_leopard/snowleopard_firefox_42.config.yml
  - CONFIG_FILE=osx/snow_leopard/snowleopard_safari_5-1.config.yml
  - CONFIG_FILE=windows/win_10/win10_chrome_37.config.yml
  - CONFIG_FILE=windows/win_10/win10_chrome_59.config.yml
  - CONFIG_FILE=windows/win_10/win10_firefox_32.config.yml
  - CONFIG_FILE=windows/win_10/win10_firefox_68esr.config.yml
  - CONFIG_FILE=windows/win_10/win10_firefox_75.config.yml
  - CONFIG_FILE=windows/win_10/win10_edge_81.config.yml
  - CONFIG_FILE=windows/win_10/win10_ie_11.config.yml
  - CONFIG_FILE=windows/win_8/win8_chrome_22.config.yml
  - CONFIG_FILE=windows/win_8/win8_chrome_81.config.yml
  - CONFIG_FILE=windows/win_8/win8_firefox_32.config.yml
  - CONFIG_FILE=windows/win_8/win8_firefox_75.config.yml
  - CONFIG_FILE=windows/win_8/win8_edge_81.config.yml
  - CONFIG_FILE=windows/win_8/win8_ie_10.config.yml
  - CONFIG_FILE=windows/xp/xp_chrome_14.config.yml
  - CONFIG_FILE=windows/xp/xp_chrome_28.config.yml
  - CONFIG_FILE=windows/xp/xp_chrome_43.config.yml
  - CONFIG_FILE=windows/xp/xp_firefox_5.config.yml
  - CONFIG_FILE=windows/xp/xp_firefox_45esr.config.yml
  - CONFIG_FILE=windows/xp/xp_firefox_47.config.yml
  - CONFIG_FILE=windows/xp/xp_ie_7.config.yml
jobs:
  include:
    - name: "Full Test Suite 2.5.3"
      rvm: 2.5.3
      env: CONFIG_FILE=windows/win_10/win10_chrome_81.config.yml
      script: bundle exec rake
    - name: "Full Test Suite 2.6.0"
      rvm: 2.6.0
      env: CONFIG_FILE=windows/win_10/win10_chrome_81.config.yml
      script: bundle exec rake
    - name: "Full Test Suite 2.6.3"
      rvm: 2.6.3
      env: CONFIG_FILE=windows/win_10/win10_chrome_81.config.yml
      script: bundle exec rake
    - name: "Full Test Suite 2.6.5"
      rvm: 2.6.5
      env: CONFIG_FILE=windows/win_10/win10_chrome_81.config.yml
      script: bundle exec rake
    - name: "Full Test Suite 2.7.0"
      rvm: 2.7.0
      env: CONFIG_FILE=windows/win_10/win10_chrome_81.config.yml
      script: bundle exec rake
script:
  - bundle exec rspec --tag run_on_browserstack
addons:
  apt:
    packages:
    - libsqlite3-dev
    - build-essential
    - patch
    - ruby-dev
    - zlib1g-dev
    - liblzma-dev
    - libcurl4-openssl-dev
  browserstack:
    username:
      secure: "d68JXyI6osz+3WF4PI+QhBfAMgdB7qFK0pQuMHDkVFy+LWfpp2LXuxYGLfhbB2anZoPDUt1R/4DPhFloO68C4+piM3lCg9OjvnuyKVWGs0rSyEH1xt4qEibSpsRYcPg8S/xeEiArHDc0/oPk+SftL79o2oIK2hEuoyL+Hd+WLPIpWB8mU+Gyi42G/QaUrl1iuQa8wqEy7NfDHM5zARp389zY4DT7j3Z+UMb5sGYkToGRB2HDX35gy2YJVWEvrFCR3DsZr2SwuPgt/F4T2ZrC+HCEf453ZmnBEorRm+6M232ez8tk5WFslGTVEJgFQj3B4NdIvbURfwWPgswuiB6N0ZmiMOuCHYM0zOw/rfI8lfT+9iJ+5t+vnMFBgUJQERG6JtIBP13nQUHBKoxGRcvWct+Weep28UoKqH00h5PYGyp+CSsCUB7CrP0foR21q6YKmzVnDSkdc3BNAYIhKahUEnA1CYOdLsLs15QL69AbsGUGk+10RefMJcv3MIBbNh+a9Nog+p54UyhGI7FuyGIYI2noxHfRmQJ7enheCZVA7DARNFqA2Z8OYtMz78wF9RSzu2B77gfEeNHyv4tanf1f5N0qBfO7e2lz3rckrj/vqQRB5WtKtEJ8Ql2d0X0fgd9h8TIJpL5T2rpEmbZepp/kp/0IA/s9o97b/vvvCawacZU="
    access_key:
      secure: "gqiyqiH4bV1EuHlcs5hmihCmZnqmll1ZhEGTFVsmI9ntnMRkbB8dnCNDjf76s4+GqA7oTrWDrERLnU2c05kEFuEY63I/BClNKKRfwp/usnIVE2xypIfSGpfbiuk1mxKpkzmPGZjIeuSoCNLAT4Vbp61bD0LlQCQKNXwhHsw8SzFs2NVk3iGdd98xkDnubTCGyLQlO4ytCy1FUISEgmMhz33tOyUwCbTQw0bpr2XNt+2GAR7MWNOmVzoKQfEX6RRSgKjDWwPbyyLl77eyj5usMJXFEbb1e/NSlb78YjZwTV+Cp/AMKzpMBNQ+MOIDQHnuQfmab8P5A5TKxOJFB+Af6dGts4Qk5KLLOe8/9w24DRSee2rXdHxTIv3hbGqJ54zZ7txD2qPndivvq0LbYYxNctbfTcopCsHyjr+NqKy9BC4SpsZ87zhlelbzcA9frkzTNQJoWJGgk9a8wqLwevAO9e0pU1KTYSPS6Qj0Nrc2N2iaveWtTFAi3QbhDRp4nrxwmiIUHUAWLQCfMfKMK7XDVbZZuCSwCzZvLCULdJh5wH6Ha52nuiwFhe/wRub85+gyKRTQrYMOddAYkTGg8aG/LgPIUaWOLkjYhj4DGMFH0ibA7Wn3aR8N1CPIG4Yf9JX9GaiVZ9dGcM2qZ8aeys5epgUSeZjOivy0kFtwK154oWg="