language: ruby
rvm:
- 2.5.3
- 2.6.0
- 2.6.3
- 2.6.5
- 2.7.0
branches:
  only:
  - master
  - browserstack
before_script:
  - RUBY_VERSION=/bin/bash rvm current
  - sed -i -E 's/system\((.*?)\)/""/g' /home/travis/.rvm/gems/$RUBY_VERSION/gems/browserstack-local-1.3.0/lib/browserstack/local.rb
env:
  - CONFIG_FILE=osx/catalina/catalina_chrome_39.config.yml
  - CONFIG_FILE=osx/catalina/catalina_chrome_59.config.yml
  - CONFIG_FILE=osx/catalina/catalina_chrome_81.config.yml
  - CONFIG_FILE=osx/catalina/catalina_firefox_11.config.yml
  - CONFIG_FILE=osx/catalina/catalina_firefox_68esr.config.yml
  - CONFIG_FILE=osx/catalina/catalina_firefox_75.config.yml
  - CONFIG_FILE=osx/catalina/catalina_safari_13.config.yml
  - CONFIG_FILE=osx/el_capitan/elcapitan_chrome_14.config.yml
  - CONFIG_FILE=osx/el_capitan/elcapitan_chrome_81.config.yml
  - CONFIG_FILE=osx/el_capitan/elcapitan_firefox_5.config.yml
  - CONFIG_FILE=osx/el_capitan/elcapitan_firefox_75.config.yml
  - CONFIG_FILE=osx/el_capitan/elcapitan_safari_9-1.config.yml
  - CONFIG_FILE=osx/snow_leopard/snowleopard_chrome_14.config.yml
  - CONFIG_FILE=osx/snow_leopard/snowleopard_chrome_35.config.yml
  - CONFIG_FILE=osx/snow_leopard/snowleopard_chrome_49.config.yml
  - CONFIG_FILE=osx/snow_leopard/snowleopard_firefox_5.config.yml
  - CONFIG_FILE=osx/snow_leopard/snowleopard_firefox_38esr.config.yml
  - CONFIG_FILE=osx/snow_leopard/snowleopard_firefox_42.config.yml
  - CONFIG_FILE=osx/snow_leopard/snowleopard_safari_5-1.config.yml
  - CONFIG_FILE=windows/win_10/win10_chrome_37.config.yml
  - CONFIG_FILE=windows/win_10/win10_chrome_59.config.yml
  - CONFIG_FILE=windows/win_10/win10_firefox_32.config.yml
  - CONFIG_FILE=windows/win_10/win10_firefox_68esr.config.yml
  - CONFIG_FILE=windows/win_10/win10_firefox_75.config.yml
  - CONFIG_FILE=windows/win_10/win10_edge_81.config.yml
  - CONFIG_FILE=windows/win_10/win10_ie_11.config.yml
  - CONFIG_FILE=windows/win_8/win8_chrome_22.config.yml
  - CONFIG_FILE=windows/win_8/win8_chrome_81.config.yml
  - CONFIG_FILE=windows/win_8/win8_firefox_32.config.yml
  - CONFIG_FILE=windows/win_8/win8_firefox_75.config.yml
  - CONFIG_FILE=windows/win_8/win8_edge_81.config.yml
  - CONFIG_FILE=windows/win_8/win8_ie_10.config.yml
  - CONFIG_FILE=windows/xp/xp_chrome_14.config.yml
  - CONFIG_FILE=windows/xp/xp_chrome_28.config.yml
  - CONFIG_FILE=windows/xp/xp_chrome_43.config.yml
  - CONFIG_FILE=windows/xp/xp_firefox_5.config.yml
  - CONFIG_FILE=windows/xp/xp_firefox_45esr.config.yml
  - CONFIG_FILE=windows/xp/xp_firefox_47.config.yml
  - CONFIG_FILE=windows/xp/xp_ie_7.config.yml
jobs:
  include:
    - name: "Full Test Suite 2.5.3"
      rvm: 2.5.3
      env: CONFIG_FILE=windows/win_10/win10_chrome_81.config.yml
      script: bundle exec rake
    - name: "Full Test Suite 2.6.0"
      rvm: 2.6.0
      env: CONFIG_FILE=windows/win_10/win10_chrome_81.config.yml
      script: bundle exec rake
    - name: "Full Test Suite 2.6.3"
      rvm: 2.6.3
      env: CONFIG_FILE=windows/win_10/win10_chrome_81.config.yml
      script: bundle exec rake
    - name: "Full Test Suite 2.6.5"
      rvm: 2.6.5
      env: CONFIG_FILE=windows/win_10/win10_chrome_81.config.yml
      script: bundle exec rake
    - name: "Full Test Suite 2.7.0"
      rvm: 2.7.0
      env: CONFIG_FILE=windows/win_10/win10_chrome_81.config.yml
      script: bundle exec rake
script:
  - bundle exec rspec --tag run_on_browserstack
addons:
  apt:
    packages:
    - libsqlite3-dev
    - build-essential
    - patch
    - ruby-dev
    - zlib1g-dev
    - liblzma-dev
    - libcurl4-openssl-dev
  browserstack:
    username:
      secure: "pQdUuMHWsDtT6v86yS91JlqcIvVa8d6Oz4tykWrE4yrRH/SH3ZsCKcNLxghZqq0EnAQC3ErJ7AlIlhZN7gDVoDOQQ3cfnLLZlTBrE38WyN6P3tae0PlDbijFncDEurKQ/RM04DYmKbhcrSzbMAjwdyvl1sufyOZ0V6iL3tZ6NXjqzPihvNQWyQH/xlGGD9erkLRY8+rNmRpVqGGV+/c0x91/vWHRuC3aIfvsSvNyGGlhebijRMKkijvolTGQdBCVuRjq7IP+6fqAkKJCvHbFTWnZcrH2f5Mp0ARjx01omZ5drY3dqu2mqNsGSgxlLKL4+K+fx14Cp1MidyZZ8N169Z8vqldQOB17apYdmoMk+crASvxNOLG+eulzJkQvB1X6FPs66hDvcqh4kmdRrvsvxVe1EodkA1Ai7urKiRU6qqy0sKVYgxf/AEYMHSwMb5zcJeJmsTMmXXIWC5lWdtsqtKKOtP0NZH/vdHrEWiGQFEGNjve2zuDdYW/ite7BnFjX4mYm9QTZ06TXZ1n9fRTF5guXc24haNKTUyM7q9JKxV0sSBroTmh9VSufpBA0uM5FhelXXuNRUImnDa/74eTKl5bmmyNDfpDiby8Vbvq2qzp93vohz/l+uW0Wg1ck4x2SgpqW0/W9Qo1QVvmF+3wHbYOVBxpZxS0jvlYvbUAxAGc="
    access_key:
      secure: "OaO0mV68t0RvWxQFdbcKCnlE5LNmFp8x9JJZG2GMMP5aIGtr/dHSKP5wSTud6oKklbyEwmzmKUljga6sg52lkBIDgLk5i+XkfCIR3YjqHAjY94akMie5JK2onUJtmBSYK9OEkUdSC16BTet1Hqb5EnqhnlECc4rF05TlcwupfQwKO2bZ5NqmUs+PKmyR2zKM6TFe1nbiAC7VVs97NMoJjzmDydy3goCNwMgOG2H4OFXB9mPlX+IBCh4i5lOJhfZeytA1enlpRZ7zY6rcJ1EjaRedmsN7/Tnan3duMiPPPY80/cGub6a3kIpCd5TQ3bHMicAYkxevkouPG2aDaND70X/MmxctrDvzmyxlUAYfebsPNqZIKn0OQb5v51h0IjO8Q0vrkPnCzmAjDkVThdRTQIMs7lIJnTOQ+/Do5lZDsEO/hysABdWD+jzoZ5EQzbMBwxqB2VVqU1XVRDBKxdQMmVqDk7zeUTaNOD2FEji3AC2EW4uBJP1J0uhCmLE2KnLFEV1xzAZCZgJIsqLpv/sDy6gN6XxnUe6BcIJ68+cToCUqH0EUMOtDp+hJ2Ei9zPfGBtCYe8msbUpO4KAThwXtj/rWIv3i3nunQOFU9y3/qXZpRFRQmuVt7WBUVi51SK2A8e2M5fzGD4xuO7tVGAbaFLnjQLJKAA95XbWileHpH3M="
