server: "hub-cloud.browserstack.com"

common_caps:
  "build": "OSX Catalina Firefox 11"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false
  "browserstack.selenium_version": "3.5.2"

browser_caps:
  -
    "browser": "firefox"
    "browser_version": "11.0"
    "os": "osx"
    "os_version": "catalina"