server: "hub-cloud.browserstack.com"

common_caps:
  "build": "OSX Snow Leopard Firefox 5"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false

browser_caps:
  -
    "browser": "firefox"
    "browser_version": "5.0"
    "os": "osx"
    "os_version": "snow leopard"