beef:
    module:
        iframe_above:
            enable: true
            category: "Persistence"
            name: "iFrame Persistance"
            description: "Rewrites all links on the webpage to spawn a 100% by 100% iFrame with a source relative to the selected link."
            authors: ["passbe"]
            target:
                user_notify: ["ALL"]
