server: "hub-cloud.browserstack.com"

common_caps:
  "build": "OSX El Capitan Chrome 14"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false
  "browserstack.selenium_version": "3.5.2"

browser_caps:
  -
    "browser": "chrome"
    "browser_version": "14.0"
    "os": "osx"
    "os_version": "el capitan"