beef:
    module:
        site_redirect:
            enable: true
            category: "Browser"
            name: "Site Redirect"
            description: "This module will redirect the selected hooked browser to the address specified in the 'Redirect URL' input."
            authors: ["wade", "vo"]
            target:
                user_notify: ["ALL"]
