server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows XP Chrome 28"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false
  "browserstack.selenium_version": "3.5.2"

browser_caps:
  -
    "browser": "chrome"
    "browser_version": "28.0"
    "os": "windows"
    "os_version": "xp"