server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows XP Chrome Latest"
  "name": "BStack Test Run"
  "project": "My Project"
  "browserstack.local": true

browser_caps:
  -
    "browser": "chrome"
    "os": "windows"
    "os_version": "xp"