server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows XP Firefox 16"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false
  "browserstack.selenium_version": "2.53.0"

browser_caps:
  -
    "browser": "firefox"
    "browser_version": "16.0"
    "os": "windows"
    "os_version": "xp"