server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows XP IE 6"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false

browser_caps:
  -
    "browser": "internet explorer"
    "browser_version": "6.0"
    "os": "windows"
    "os_version": "xp"