server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows 7 IE 8"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false

browser_caps:
  -
    "browser": "internet explorer"
    "browser_version": "8.0"
    "os": "windows"
    "os_version": "7"