beef:
    module:
        link_rewrite:
            enable: true
            category: "Browser"
            name: "Link Rewriter"
            description: "This module will rewrite all the href attributes of all matched links.<br /><br />The jQuery selector field can be used to limit the selection of links. eg: a[href=\"http://www.bindshell.net\"]. For more information please see: http://api.jquery.com/category/selectors/"
            authors: ["passbe"]
            target:
                working: ["ALL"]
