server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows 10 Firefox 75"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false
  "browserstack.selenium_version": "3.10.0"

browser_caps:
  -
    "browser": "firefox"
    "browser_version": "75.0"
    "os": "windows"
    "os_version": "10"