server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows 10 Chrome 37"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false
  "browserstack.selenium_version": "3.5.2"

browser_caps:
  -
    "browser": "chrome"
    "browser_version": "37.0"
    "os": "windows"
    "os_version": "10"