server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows 10 Chrome 37"
  "name": "BStack Test Run"
  "project": "My Project"
  "browserstack.local": true

browser_caps:
  -
    "browser": "chrome"
    "browser_version": "37.0"
    "os": "windows"
    "os_version": "10"