server: "hub-cloud.browserstack.com"
user: "craigdonaldson1"
key: "%BROWSERSTACK_ACCESS_KEY%"

common_caps:
  "build": "rspec-browserstack"
  "browserstack.debug": true
  "name": "BStack Test Run"

browser_caps:
  # OS Specific Browsers
  -
    "browser": "safari"
    "os": "OS X"
  -
    "browser": "edge"
    "os": "Windows"
  -
    "browser": "internet explorer"
    "os": "Windows"
  # Multi-OS Browsers
  -
    "browser": "chrome"
    "os": "OS X"
  -
    "browser": "chrome"
    "os": "Windows"
  -
    "browser": "firefox"
    "os": "OS X"
  -
    "browser": "firefox"
    "os": "Windows"