server: "hub-cloud.browserstack.com"
user: "craigdonaldson1"
key: $BROWSERSTACK_ACCESS_KEY

common_caps:
  "build": "rspec-browserstack"
  "browserstack.debug": true
  "name": "BStack Test Run"

browser_caps:
  -
    "browser": "chrome"
    "os": "OS X"