server: "hub-cloud.browserstack.com"

common_caps:
  "build": "OSX Safari"
  "browserstack.debug": true
  "name": "BStack Test Run"
  "project": "My Project"

browser_caps:
  -
    "browser": "safari"
    "os": "OS X"