server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows Chrome"
  "browserstack.debug": true
  "name": "BStack Test Run"
  "project": "My Project"

browser_caps:
  -
    "browser": "chrome"
    "os": "Windows"