server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows Edge"
  "browserstack.debug": true
  "name": "BStack Test Run"
  "project": "My Project"

browser_caps:
  -
    "browser": "edge"
    "os": "Windows"