server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows IE"
  "browserstack.debug": true
  "name": "BStack Test Run"

browser_caps:
  -
    "browser": "internet explorer"
    "os": "Windows"