server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows Firefox"
  "browserstack.debug": true
  "name": "BStack Test Run"

browser_caps:
  -
    "browser": "firefox"
    "os": "Windows"