beef:
    module:
        site_redirect_iframe:
            enable: true
            category: "Browser"
            name: "Site Redirect (iframe)"
            description: "This module will redirect the selected hooked browser to the address specified in the 'Redirect URL' input. It creates a 100% x 100% overlaying iframe to keep the victim hooked and changes the page title to the provided value which should be set to the title of the redirect URL."
            authors: ["ethicalhack3r", "Yori Kvitchko"]
            target:
                user_notify: ["ALL"]
