beef:
    module:
        coldfusion_dir_traversal_exploit:
            enable: true
            category: "Network"
            name: "ColdFusion Directory Traversal Exploit"
            description: "ColdFusion 9.0, 8.0.1, 9.0 and 9.0.1 are vulnerable to directory traversal that leads to arbitrary file retrieval from the ColdFusion server (CVE-2010-2861)"
            authors: ["antisnatchor"]
            target:
                working: ["ALL"]
