beef:
    module:
        detect_soc_nets:
            enable: true
            category: "Recon"
            name: "Detect Social Networks"
            description: "This module will detect if the Hooked Browser is currently authenticated to GMail, Facebook and Twitter."
            authors: ["xntrik", "Mike Cardwell"]
            target:
                working: ["ALL"]
