beef:
    module:
        detect_screen_details:
            enable: true
            category: "Browser"
            name: "Screen Details"
            description: "This module will retrieve the selected hooked browser screen dimensions."
            authors: ["wade", "vo", "passbe", "saafan"]
            target:
                working: ["ALL"]
