beef:
    module:
        detect_details:
            enable: true
            category: "Browser"
            name: "Browser Type"
            description: "This module will retrieve the selected hooked browser details."
            authors: ["wade", "vo", "passbe", "saafan"]
            target:
                working: ['ALL']
