beef:
    module:
        linksys_befsr41_csrf:
            enable: true
            category: "Network"
            name: "Linksys BEFSR41 CSRF Exploit"
            description: "Attempts to enable remote administration and change the password on a Linksys BEFSR41 router."
            authors: ["Martin Barbella"]
            target:
                working: ["ALL"]
