server: "hub-cloud.browserstack.com"

common_caps:
  "build": "Windows 8 Firefox 32"
  "project": "BeEF"
  "browserstack.local": true
  "browserstack.video": false
  "browserstack.selenium_version": "3.5.2"

browser_caps:
  -
    "browser": "firefox"
    "browser_version": "32.0"
    "os": "windows"
    "os_version": "8"