server: "hub-cloud.browserstack.com"

common_caps:
  "build": "OSX Safari"
  "name": "BStack Test Run"
  "project": "My Project"
  "browserstack.local": true

browser_caps:
  -
    "browser": "safari"
    "os": "OS X"